baseURL = "https://vupham-rainn.github.io/blog-laptrinhmang/"
publishDir = "docs"

languageCode = "vi"
title = "Blog L·∫≠p Tr√¨nh M·∫°ng"
theme = "PaperMod"

[pagination]
  pagerSize = 9

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  showtoc = true

  [params.assets]
    disableFingerprinting = true

[params.homeInfoParams]
  Title = "Xin ch√†o üëã"
  Content = "ƒê√¢y l√† blog c√° nh√¢n chia s·∫ª ki·∫øn th·ª©c l·∫≠p tr√¨nh m·∫°ng, Java & JavaScript."

[menu]
  [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url  = "/posts/"
  weight = 2

  [[menu.main]]
  name = "Profile"
  url  = "/profile/"
  weight = 3

 [[menu.main]]
name = "Ch·ª©ng ch·ªâ"
url  = "/chung-chi/"
weight = 4

